server:
  port: 5000
spring:
  main:
    allow-bean-definition-overriding: true
    output:
      ansi:
        enabled: always

  jackson:
    mapper:
      accept-case-insensitive-properties: true

  datasource:
    hikari:
      maximum-pool-size: 40
    url: jdbc:postgresql://rcp-manager.cn6bq9wf3qhu.us-east-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: doXzoTWX1M3OUNaeK9hH

  jpa:
    show-sql: false
    properties:
      hibernate:
        default_schema: recipe
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
    hibernate:
      ddl-auto: update

service:
  user:
    restriction:
      max-incomplete: 10
      minIngredients: 1
      minSteps: 2
  apple:
    key-id: 89S3CH632C
    team-id: 4NW94WU93C
    client-id: com.foodcrunch.foodmonster
    apple-auth-url: https://appleid.apple.com/auth/token
    apple-revoke-url: https://appleid.apple.com/auth/revoke

security:
  firebase-props:
    database-url: https://slowcooker-a725e.firebaseio.com
    enable-strict-server-session: false
    enable-check-session-revoked: false
    enable-logout-everywhere: false
    session-expiry-in-days: 5
  cookie-props:
    max-age-in-minutes: 7200
    http-only: true
    secure: true
#    domain: ${DOMAIN}
    path: /
  allow-credentials: true
  allowed-origins:
#    - https://${DOMAIN}
    - http://localhost:8080
  allowed-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allowed-headers:
    - Authorization
    - Origin
    - Content-Type
    - Accept
    - Accept-Encoding
    - Accept-Language
    - Access-Control-Allow-Origin
    - Access-Control-Allow-Headers
    - Access-Control-Request-Method
    - X-Requested-With
    - X-Auth-Token
    - X-Xsrf-Token
    - Cache-Control
    - Id-Token
  allowed-public-apis:
    - /favicon.ico
    - /session/login
    - /public/**
  exposed-headers:
    - X-Xsrf-Token