spring:
  main:
    allow-bean-definition-overriding: true
    output:
      ansi:
        enabled: always

  jackson:
    mapper:
      accept-case-insensitive-properties: true

  datasource:
    url: jdbc:postgresql://ec2-34-203-155-237.compute-1.amazonaws.com:5432/d7pntfk4v8p94d
    username: crqbgdhunawynu
    password: 3a083ec451cb103fb944e947be4cfbae43be02d7bfeaf9991a23183085b0601b

  jpa:
    show-sql: false
    properties:
      hibernate:
        default_schema: recipe
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
    hibernate:
      ddl-auto: update