spring:
  main:
    allow-bean-definition-overriding: true
    output:
      ansi:
        enabled: always

  jackson:
    mapper:
      accept-case-insensitive-properties: true

  datasource:
    url: jdbc:postgresql://ec2-3-225-41-234.compute-1.amazonaws.com:5432/d8jhvfv2mluheo
    username: ldysxlweoguazb
    password: bfd875e47e33a8c99562e501b39ec0ec16505f806f87af9899b4f257b40879ee

  jpa:
    show-sql: false
    properties:
      hibernate:
        default_schema: recipe
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
    hibernate:
      ddl-auto: update

security:
  firebase-props:
    database-url: https://slowcooker-a725e.firebaseio.com
    enable-strict-server-session: false
    enable-check-session-revoked: false
    enable-logout-everywhere: false
    session-expiry-in-days: 5
  cookie-props:
    max-age-in-minutes: 7200
    http-only: true
    secure: true
#    domain: ${DOMAIN}
    path: /
  allow-credentials: true
  allowed-origins:
#    - https://${DOMAIN}
    - http://localhost:8080
  allowed-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allowed-headers:
    - Authorization
    - Origin
    - Content-Type
    - Accept
    - Accept-Encoding
    - Accept-Language
    - Access-Control-Allow-Origin
    - Access-Control-Allow-Headers
    - Access-Control-Request-Method
    - X-Requested-With
    - X-Auth-Token
    - X-Xsrf-Token
    - Cache-Control
    - Id-Token
  allowed-public-apis:
    - /favicon.ico
    - /session/login
    - /public/**
  exposed-headers:
    - X-Xsrf-Token